# Generated by Django 5.2.6 on 2025-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
