# Generated by Django 5.2.6 on 2025-10-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_attendancelevel_course_day_paymenttype_rooms_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField()),
            ],
        ),
    ]
