# Generated by Django 5.2.6 on 2025-10-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0005_remove_student_user_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemodel',
            name='date',
        ),
        migrations.AddField(
            model_name='student',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
