# Generated by Django 5.2.6 on 2025-10-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0006_remove_tablemodel_date_student_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=123),
        ),
    ]
