# Generated by Django 5.2.6 on 2025-10-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0008_rename_password_student_passwords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='groups',
            new_name='group',
        ),
    ]
