# Generated by Django 5.2.6 on 2025-10-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0009_rename_groups_teacher_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='table',
        ),
    ]
