# Generated by Django 5.2.6 on 2025-10-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0010_remove_group_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_group',
            field=models.ManyToManyField(blank=True, related_name='students', to='configapp.group'),
        ),
    ]
