# Generated by Django 5.2.6 on 2025-10-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0011_student_s_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='otp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
