# Generated by Django 5.2.6 on 2025-10-12 16:00

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0012_student_otp_teacher_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(verbose_name=django.db.models.fields.DateTimeField),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ManyToManyField(to='configapp.student'),
        ),
    ]
