# Generated by Django 5.2.6 on 2025-10-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0013_alter_attendance_created_remove_attendance_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(related_name='attendances', to='configapp.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
