# Generated by Django 5.2.6 on 2025-10-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0014_remove_attendance_student_attendance_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('failed_students', models.ManyToManyField(blank=True, related_name='failed_exams', to='configapp.student')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='configapp.group')),
                ('passed_students', models.ManyToManyField(blank=True, related_name='passed_exams', to='configapp.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='configapp.teacher')),
            ],
        ),
    ]
