# Generated by Django 5.2.6 on 2025-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0015_alter_attendance_created_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateField(default='2025-09-14'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(default='2025-09-14'),
        ),
    ]
