# Generated by Django 5.2.6 on 2025-10-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0016_student_created_student_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
    ]
