# Generated by Django 5.2.6 on 2025-10-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0017_remove_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_activate',
            field=models.CharField(default='activmas'),
        ),
    ]
